# Generated by Django 3.2 on 2022-03-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.TextField(choices=[('MV', 'movie'), ('TV', 'tv_show')], default='MV', verbose_name='type'),
        ),
    ]
