version: '3'
services:
  database:
    image: 'postgres:13'
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./imports/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
    expose:
      - 8000
    env_file:
      - .env
      - ./app/config/.env
    depends_on:
      - database


  nginx:
    image: nginx
    volumes:
      - /var/www/django/static:/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - backend
    ports:
      - "80:80"
